### ISSUE TITLE
程序使用问题

### ISSUE THREAD

**Issue by Herbert860797** [lovebili/bilibili_show#1]
1、请问在运行演出购票时，报错
Traceback (most recent call last):
  File "C:\Users\herbe\Desktop\bilibili_show-main\会员购漫展演出购票.py", line 25, in <module>
    with open('./config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './config.json'
怎么解决

2、还有请问
如何设置同时抢多张票并选择预设购票人信息中的人

**Comment by JEFF666888** [comment]
报错   No such file or directory: './config.json'
咋办

**Comment by lovebili** [comment]
你好，
可以把运行该脚本所在目录的截图发给我看，检验一下吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lovebili/bilibili_show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月8日(星期六) 下午2:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [lovebili/bilibili_show] 程序使用问题 (Issue #1)





 
报错   No such file or directory: './config.json'
 咋办

**Comment by lovebili** [comment]
你好，
麻烦加我qq1948370049
方便沟通


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lovebili/bilibili_show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月8日(星期六) 下午2:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [lovebili/bilibili_show] 程序使用问题 (Issue #1)





 
报错   No such file or directory: './config.json'
 咋办

**Comment by Herbert860797** [comment]
![JZAI%KE~F6BR{5}6I7E_LN4](https://github.com/lovebili/bilibili_show/assets/129668457/b871344e-1399-454d-b190-ea133b3479cb)

**Comment by JEFF666888** [comment]
![image](https://github.com/lovebili/bilibili_show/assets/71984098/5767c9d8-b78b-4439-87c5-dd897ef22345)

**Comment by yuukiyuuna** [comment]
> 1、请问在运行演出购票时，报错 Traceback (most recent call last): File "C:\Users\herbe\Desktop\bilibili_show-main\会员购漫展演出购票.py", line 25, in with open('./config.json', 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: './config.json' 怎么解决
> 
> 2、还有请问 如何设置同时抢多张票并选择预设购票人信息中的人

这个问题我也遇到了，看了一下代码处理cookie的格式不对，不知道是不是b站换过cookie格式的

你在 “[使用cookie实现登录b站.py](https://github.com/lovebili/bilibili_show/blob/main/%E4%BD%BF%E7%94%A8cookie%E5%AE%9E%E7%8E%B0%E7%99%BB%E5%BD%95b%E7%AB%99.py)”中把 for cookie in listcookie:  改成  for cookie in listcookie['bilibili_cookies'][0]


然后在 “[上海·BilibiliWorld 2023 购票-会员](https://github.com/lovebili/bilibili_show/blob/main/%E4%B8%8A%E6%B5%B7%C2%B7BilibiliWorld%202023%20%E8%B4%AD%E7%A5%A8-%E4%BC%9A%E5%91%98)”中把  for cookie in config["bilibili_cookies"]:  改成 for cookie in config["bilibili_cookies"][0]:


就可以用了

**Comment by 1486308032** [comment]
> > 1、请问在运行演出购票时，报错 Traceback (most recent call last): File "C:\Users\herbe\Desktop\bilibili_show-main\会员购漫展演出购票.py", line 25, in with open('./config.json', 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: './config.json' 怎么解决
> > 2、还有请问 如何设置同时抢多张票并选择预设购票人信息中的人
> 
> 这个问题我也遇到了，看了一下代码处理cookie的格式不对，不知道是不是b站换过cookie格式的
> 
> 你在 “[使用cookie实现登录b站.py](https://github.com/lovebili/bilibili_show/blob/main/%E4%BD%BF%E7%94%A8cookie%E5%AE%9E%E7%8E%B0%E7%99%BB%E5%BD%95b%E7%AB%99.py)”中把 for cookie in listcookie: 改成 for cookie in listcookie['bilibili_cookies'][0]
> 
> 然后在 “[上海·BilibiliWorld 2023 购票-会员](https://github.com/lovebili/bilibili_show/blob/main/%E4%B8%8A%E6%B5%B7%C2%B7BilibiliWorld%202023%20%E8%B4%AD%E7%A5%A8-%E4%BC%9A%E5%91%98)”中把 for cookie in config["bilibili_cookies"]: 改成 for cookie in config["bilibili_cookies"][0]:
> 
> 就可以用了

可以尝试[会员购通用脚本](https://github.com/lovebili/bilibili_show/tree/main/%E4%BC%9A%E5%91%98%E8%B4%AD%E9%80%9A%E7%94%A8%E8%84%9A%E6%9C%AC)，使用xpath匹配并不可靠
